version: '3.2'

services:
  api-service-1:
    build:
      context: ./web-api
#    network_mode: "host"
    extra_hosts:
      - "172.17.0.3:127.0.0.3"
    volumes:
      - ./web-api:/usr/src/app
    ports:
      - 5001:8080

  api-service-2:
    build:
      context: ./web-api
#    network_mode: "host"
    extra_hosts:
      - "127.0.0.3:172.17.0.1"
    volumes:
      - ./web-api:/usr/src/app
    ports:
      - 5002:8080

  api-service-3:
    build:
      context: ./web-api
#    network_mode: "host"
    extra_hosts:
      - "db_host:127.0.0.3"
    volumes:
      - ./web-api:/usr/src/app
    ports:
      - 5003:8080
