apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: octu
    tier: backend
spec:
  clusterIP: 10.152.183.42 
  ports:
  - port: 6379
    targetPort: 8880
  selector:
    app: octu
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octu 
      tier: backend
  template:
    metadata:
      labels:
        app: octu 
        tier: backend
    spec:
      containers:
      - name: main
        image: octu:local
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 400m
            memory: 500Mi
        ports:
        - containerPort: 8880
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
    tier: backend
spec:
  clusterIP: 10.152.183.95 
  ports:
  - port: 6381
    targetPort: 5432
  selector:
    app: db
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db 
      tier: backend
  template:
    metadata:
      labels:
        app: db 
        tier: backend
    spec:
      containers:
      - name: main
        image: postgres:latest
        env:
          - name: "POSTGRES_HOST_AUTH_METHOD"
            value: "trust"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 400m
            memory: 500Mi
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    app: broker
    tier: backend
spec:
  ports:
  - port: 6380
  selector:
    app: broker
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker 
      tier: backend
  template:
    metadata:
      labels:
        app: broker
        tier: backend
    spec:
      containers:
      - name: mosquitto 
        image: eclipse-mosquitto:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 400m
            memory: 500Mi
        ports:
        - containerPort: 6380

      - name: mimic
        image: mimic:local
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
         - containerPort: 6382

       #env:
       # - name: GET_HOSTS_FROM
       #   value: dns
          # If your cluster config does not include a dns service, then to
          # instead access an environment variable to find the master
          # service's host, comment out the 'value: dns' line above, and
          # uncomment the line below:
          # value: env
        
