- name: "Instaling python3.7 dependecies"
  apt:
    name: "{{ py3.7-packages }}"

- name: "Installing git dependencies"
  apt:
    name: "{{ git-packages }}"

- name: "Installing bazel-tensorflow dependencies"
  apt:
    name: "{{ tf-packages }}"

- name: "Installing general packages"
  apt:
    name: "{{ gen-packages }}"

- name: "Installing postgresql"
  apt:
    name: "{{ postgres-packages }}"

