- name: "Preparing vars"
  include_vars: "{{ install_type }}.yaml"

- name: "Installing python3.7 {{ type_packages }}"
  apt:
    name: "{{ py3.7-packages }}"

- name: "Installing git dependencies"
  apt:
    name: "{{ git-deps }}"
  when: server

- name: "Installing bazel-tensorflow dependencies"
  apt:
    name: "{{ tf-deps }}"
  when: server

- name: "Installing general packages"
  apt:
    name: "{{ gen-packages }}"

- name: "Installing postgresql"
  apt:
    name: "{{ postgres-packages }}"

