type_packages: "packages"
server: false

# Packages for installing python3.7
py3.7-packages:
  - build-essential
  - checkinstall
  - libreadline-gplv2-dev
  - libncursesw5-dev
  - libssl-dev
  - libsqlite3-dev
  - tk-dev
  - libgdbm-dev
  - libc6-dev
  - libbz2-dev
  - zlib1g-dev
  - openssl
  - libffi-dev
  - python3-dev
  - python3-setuptools
  - wget

# General purpose packages for the server
gen-packages:
  - vim
  - nano
  - git
  - vitualenvwrapper

# Postgresql packages for the DB
postgres-packages:
  - postgresql
  - postgresql-contrib
  - postgresql-server-dev-10

