---
type_packages: "packages"
server: false

# Packages for installing python3.7
py37_packages:
  - build-essential
  - checkinstall
  - libreadline-gplv2-dev
  - libncursesw5-dev
  - libssl-dev
  - libsqlite3-dev
  - tk-dev
  - libgdbm-dev
  - libc6-dev
  - libbz2-dev
  - zlib1g-dev
  - openssl
  - libffi-dev
<<<<<<< HEAD
  - python-dev
  - python3-dev
  - python3-setuptools
  - wget
  - python3.7
  - python3.7-dev

# General purpose packages for the server
gen_packages:
  - vim
  - nano
  - git
  - virtualenvwrapper

# Postgresql packages for the DB
postgres_packages:
  - postgresql
  - postgresql-contrib
  - postgresql-server-dev-10

