# TODO: Regex the filenames
#  Build python3.7
- debug:
    msg: Building python3.7

- name: "Extracting python src Python-3.7.4.tar.xz"
  unarchive:
    src: /tmp/src/Python-3.7.4.tar.xz
    dest: /usr/src

- name: "Configuring build"
  shell: ./configure --enable-optimizations
  args:
    chdir: /usr/src/Python-3.7.4

- name: "Making build"
  shell: make altinstall -j
  args:
    chdir: /usr/src/Python-3.7.4

#  Build git
- debug:
    msg: Building git

- name: "Extracting git src v2.23.0.tar.gz"
  unarchive:
    src: /tmp/src/v2.23.0.tar.gz
    dest: /usr/src

- name: "Configuring build"
  shell: make configure && ./configure --prefix=/usr
  args:
    chdir: /usr/src/v2.23.0
 
- name: "Making build"
  shell: make all doc info && make install install-doc install-html install-info
  args:
    chdir: /usr/src/v2.23.0

#  Build gcc
- debug:
    msg: Building gcc

- name: "Extracting gcc src gcc-9.1.0.tar.xz"
  unarchive:
    src: /tmp/src/gcc-9.1.0.tar.xz
    dest: /usr/src

- name: "Download prerequisites"
  shell: ./contrib/download_prerequisites
  args:
    chdir: /usr/src/gcc-9.1.0

- name: "Making building dir"
  shell: mkdir builddir
  args:
    chdir: /usr/src/gcc-9.1.0

- name: "Configuring build"
  shell: ../gcc-4.6.2/configure --prefix=$HOME/GCC-4.6.2 --enable-languages=c,c++,fortran,go
  args:
    chdir: /usr/src/gcc-9.1.0/builddir

    # TODO: Get machine number of cores to set param -j of parallelism automatically
- name: "Making build"
  shell: make -j && make install
  args:
    chdir: /usr/src/gcc-9.1.0/builddir

