# TODO: Regex the filenames
##
#  Build python3.7
- debug:
    msg: Building python>=3.7

- name: "Extracting python src {{ downloaded_py.dest }}"
  unarchive:
    src: "{{ downloaded_py.dest }}"
    dest: /usr/src
    list_files: True
  register: extracted_py

- name: "Configuring build"
  shell: ./configure --enable-optimizations
  args:
    chdir: "/usr/src/{{ extracted_py['files'][0] }}"

- name: "Making build"
  shell: make altinstall -j
  args:
    chdir: "/usr/src/{{ extracted_py['files'][0] }}"

##
#  Build git
- debug:
    msg: Building git

- name: "Extracting git src {{ downloaded_git.dest }}"
  unarchive:
    src: "{{ downloaded_git.dest }}"
    dest: /usr/src
    list_files: True
  register: extracted_git

- name: "Configuring build"
  shell: make configure && ./configure --prefix=/usr
  args:
    chdir: "/usr/src/{{ extracted_git['files'][0] }}"
 
- name: "Making build"
  shell: make all doc info && make install install-doc install-html install-info
  args:
    chdir: "/usr/src/{{ extracted_git['files'][0] }}"

##
#  Build gcc
- debug:
    msg: Building gcc

- name: "Extracting gcc src {{ downloaded_gcc.dest }}"
  unarchive:
    src: "/tmp/src/{{ downloaded_gcc.dest }}"
    dest: /usr/src
    list_files: True
  register: extracted_gcc

- name: "Download prerequisites"
  shell: ./contrib/download_prerequisites
  args:
    chdir: "/usr/src/{{ extracted_gcc['files'][0] }}"

- name: "Assuring building dir"
  file:
    path: "/usr/src/{{ extracted_gcc['files'][0] }}/builddir"
    state: directory

- name: "Configuring build"
  shell: "../configure --prefix=$HOME/GCC-{{ gcc_version }} --enable-languages=c,c++,fortran,go"
  args:
    chdir: "/usr/src/{{ extracted_gcc['files'][0] }}/builddir"

# TODO: Get machine number of cores to set param -j of parallelism automatically
- name: "Making build"
  shell: make -j && make install
  args:
    chdir: "/usr/src/{{ extracted_gcc['files'][0] }}/builddir"

